name: preview
on:
    push:
        branches:
            - fast_update

jobs:
    update:
        name: EAS Update and preview production
        runs-on: ubuntu-latest
        permissions:
            contents: read
            pull-requests: write
        steps:
            - name: Check for EXPO_TOKEN
              run: |
                  if [ -z "${{ secrets.EXPO_TOKEN }}" ]; then
                    echo "You must provide an EXPO_TOKEN secret linked to this project's Expo account in this repo's secrets. Learn more: https://docs.expo.dev/eas-update/github-actions"
                    exit 1
                  fi

            - name: Checkout repository
              uses: actions/checkout@v3

            - name: Setup Node
              uses: actions/setup-node@v3
              with:
                  node-version: 18.x
                  cache: yarn

            - name: Setup EAS
              uses: expo/expo-github-action@v8
              with:
                  eas-version: latest
                  token: ${{ secrets.EXPO_TOKEN }}

            - name: Install dependencies
              run: yarn install

            - name: Create update
              run: EXPO_PUBLIC_FIREBASE_API_KEY="${{ secrets.EXPO_PUBLIC_FIREBASE_API_KEY }}" EXPO_PUBLIC_FIREBASE_AUTH_DOMAIN="${{ secrets.EXPO_PUBLIC_FIREBASE_AUTH_DOMAIN }}" EXPO_PUBLIC_FIREBASE_PROJECT_ID="${{ secrets.EXPO_PUBLIC_FIREBASE_PROJECT_ID }}" EXPO_PUBLIC_FIREBASE_STORAGE_BUCKET="${{ secrets.EXPO_PUBLIC_FIREBASE_STORAGE_BUCKET }}" EXPO_PUBLIC_FIREBASE_MESSAGING_SENDER_ID="${{ secrets.EXPO_PUBLIC_FIREBASE_MESSAGING_SENDER_ID }}" EXPO_PUBLIC_FIREBASE_APP_ID="${{ secrets.EXPO_PUBLIC_FIREBASE_APP_ID }}" EXPO_PUBLIC_FIREBASE_MEASUREMENT_ID="${{ secrets.EXPO_PUBLIC_FIREBASE_MEASUREMENT_ID }}" EXPO_PUBLIC_FIREBASE_WEB_CLIENT_ID="${{ secrets.EXPO_PUBLIC_FIREBASE_WEB_CLIENT_ID }}" EXPO_PUBLIC_EXAM_FUNCTION_URL="${{ secrets.EXPO_PUBLIC_EXAM_FUNCTION_URL }}" eas update --branch production --clear-cache --message "${{ github.event.head_commit.message }}"
